apiVersion: v1
kind: ReplicationController    #类型为ReplicationController
metadata:
  name: nginx        #ReplicationController名字
spec:
  replicas: 3        #pod实例数目
  selector:          #pod选择器
    app: nginx
  template:          #pod模板
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
